# Generated by Django 6.1 on 2026-10-08 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_customerinvoice_customerinvoiceitem'),
        ('products', '0003_product_gst_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='customerinvoiceitem',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='customerinvoiceitem',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='customerinvoiceitem',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='customerinvoiceitem',
            name='total_price',
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='customer_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='payment_due',
            field=models.CharField(default='On Receipt', max_length=50),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', max_length=30),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='upi_details',
            field=models.CharField(blank=True, default='abc@upi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerinvoiceitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='customerinvoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='customerinvoiceitem',
            name='hsn_code',
            field=models.CharField(blank=True, default='6109', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerinvoiceitem',
            name='product_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customerinvoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='customerinvoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterField(
            model_name='customerinvoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
    ]
