# Generated by Django 6.1 on 2026-09-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalerprofile',
            name='retailers',
            field=models.ManyToManyField(blank=True, related_name='wholesaler', to='accounts.retailerprofile'),
        ),
    ]
