# Generated by Django 6.1 on 2026-09-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_wholesalerprofile_retailers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesalerprofile',
            name='retailers',
            field=models.ManyToManyField(blank=True, related_name='wholesalers', to='accounts.retailerprofile'),
        ),
    ]
