# Generated by Django 6.1 on 2026-09-21 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_wholesalerprofile_retailers'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_stocks', to='products.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='accounts.retailerprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('retailer', 'product'), name='unique_retailer_product_stock')],
            },
        ),
    ]
